[package]
name = "aise"
version = "2.25.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[lib]
name = "aise"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 1
panic = "abort"

[profile.release]
opt-level = "s"
debug = true
panic = "abort"
overflow-checks = true
lto = true

[dependencies]
backtrace = "0.3"
bincode = "1.0"
bitflags = "1.0"
byteorder = "1.1"
chrono = "0.4"
directories = "1.0.2"
fern = "0.5"
fxhash = "0.2.1"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
parking_lot = "0.8"
rand = "0.6"
scopeguard = "1.0"
serde = { version = "1.0.27", features = ["rc"] }
serde_derive = "1.0.27"
smallvec = "0.6"
thread_local = "0.3.5"

cgmath = { version = "0.17", optional = true }
euclid = { version = "0.19", optional = true }
glium = { version = "0.24", optional = true, default-features = false }
gl = { version = "0.12", optional = true }

[dependencies.font-kit]
git = "https://github.com/pcwalton/font-kit"
rev = "7e6a5599bd7f2b1a0166ce868e72a76086f317cb"
optional = true

[dependencies.rand_xorshift]
version = "0.1.1"
features = ["serde1"]

[dependencies.winapi]
version = "0.3.3"
features = ["heapapi", "libloaderapi", "processthreadsapi", "winuser", "wingdi"]

[dependencies.bw_dat]
path = "bw_dat"

[dependencies.whack]
git = "https://github.com/neivv/whack/"

[dependencies.samase_shim]
git = "https://github.com/neivv/samase_plugin"

[features]
opengl = ["cgmath", "euclid", "font-kit", "glium", "gl"]
