[package]
name = "ais_attackto"
version = "2.4.1"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[lib]
name = "ais_attackto"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
debug = true
panic = "abort"
overflow-checks = true

[dependencies]
backtrace = "0.3"
byteorder = "1.1"
chrono = "0.4"
fern = "0.4"
lazy_static = "0.2"
libc = "0.2"
log = "0.3"
scopeguard = "0.3.2"

[dependencies.winapi]
version = "0.3.3"
features = ["heapapi", "libloaderapi", "processthreadsapi", "winuser"]

[dependencies.whack]
git = "https://github.com/neivv/whack/"

[dependencies.bw_dat]
path = "bw_dat"
