[package]
name = "aise"
version = "2.19.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[lib]
name = "aise"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
debug = true
panic = "abort"
overflow-checks = true
lto = true

[dependencies]
backtrace = "0.3"
bincode = "1.0"
bitflags = "1.0"
byteorder = "1.1"
chrono = "0.4"
directories = "1.0.2"
fern = "0.5"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
memoffset = "0.2.1"
parking_lot = "0.6"
scopeguard = "0.3.2"
serde = { version = "1.0.27", features = ["rc"] }
serde_derive = "1.0.27"
smallvec = "0.6"
thread_local = "0.3.5"

cgmath = { version = "0.16", optional = true }
euclid = { version = "0.19", optional = true }
fnv = { version = "1.0.6", optional = true }
font-kit = { version = "0.1", optional = true }
glium = { version = "0.22", optional = true, default-features = false }
gl = { version = "0.10", optional = true }

[dependencies.rand]
version = "0.5"
features = ["serde1"]

[dependencies.winapi]
version = "0.3.3"
features = ["heapapi", "libloaderapi", "processthreadsapi", "winuser", "wingdi"]

[dependencies.bw_dat]
path = "bw_dat"

[dependencies.whack]
git = "https://github.com/neivv/whack/"

[dependencies.samase_shim]
git = "https://github.com/neivv/samase_plugin"

[features]
opengl = ["cgmath", "euclid", "fnv", "font-kit", "glium", "gl"]
