[package]
name = "aise"
version = "2.10.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[lib]
name = "aise"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
debug = true
panic = "abort"
overflow-checks = true
lto = true

[dependencies]
backtrace = "0.3"
bincode = "1.0"
bitflags = "1.0"
byteorder = "1.1"
chrono = "0.4"
fern = "0.5"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
memoffset = "0.2.1"
scopeguard = "0.3.2"
serde = "1.0.27"
serde_derive = "1.0.27"
smallvec = "0.6"
thread_local = "0.3.5"

[dependencies.rand]
version = "0.5"
features = ["serde1"]

[dependencies.winapi]
version = "0.3.3"
features = ["heapapi", "libloaderapi", "processthreadsapi", "winuser"]

[dependencies.bw_dat]
path = "bw_dat"

[dependencies.whack]
git = "https://github.com/neivv/whack/"

[dependencies.samase_shim]
git = "https://github.com/neivv/samase_plugin"
